bash: Refactor CL processing into a function
Signed-off-by: Mark Grant <m.grant.prg@gmail.com>

diff --git a/src/prg/bash/bin-deb-upl.sh.in b/src/prg/bash/bin-deb-upl.sh.in
--- a/src/prg/bash/bin-deb-upl.sh.in
+++ b/src/prg/bash/bin-deb-upl.sh.in
@@ -262,48 +262,60 @@ parse_filename()
 	return 0
 }
 
+# Process command line arguments with GNU getopt.
+# Parameters -	$1 is the command line.
+# No return value.
+proc_CL()
+{
+	local GETOPTTEMP
+	local tmpGETOPTTEMP
+
+	tmpGETOPTTEMP="getopt -o hvV --long help,verbose,version"
+	GETOPTTEMP=$($tmpGETOPTTEMP -n "$0" -- "$@")
+	std_cmd_err_handler $?
+
+	eval set -- "$GETOPTTEMP"
+	std_cmd_err_handler $?
+
+	while true; do
+		case "$1" in
+		-h|--help)
+			usage
+			shift
+			script_exit 0
+			;;
+		-v|--verbose)
+			verbose=true
+			shift
+			;;
+		-V|--version)
+			printf "Script version %s\n" $version
+			printf "Package version %s\n" $packageversion
+			shift
+			script_exit 0
+			;;
+		--)	shift
+			break
+			;;
+		*)	output "Internal error." 1
+			script_exit 1
+			;;
+		esac
+	done
+
+	# Script does not accept other arguments.
+	if [ $# -gt 0 ]; then
+		output "Invalid argument." 1
+		script_exit 1
+	fi
+}
+
 
 ########
 # Main #
 ########
-# Process command line arguments with GNU getopt.
-GETOPTTEMP=`getopt -o hvV --long help,verbose,version -n "$0" -- "$@"`
-std_cmd_err_handler $?
 
-eval set -- "$GETOPTTEMP"
-std_cmd_err_handler $?
-
-while true; do
-	case "$1" in
-	-h|--help)
-		usage
-		shift
-		script_exit 0
-		;;
-	-v|--verbose)
-		verbose=true
-		shift
-		;;
-	-V|--version)
-		echo "$0 Script version "$version
-		echo "$0 Package version "$packageversion
-		shift
-		script_exit 0
-		;;
-	--)	shift
-		break
-		;;
-	*)	output "Internal error." 1
-		script_exit 1
-		;;
-	esac
-done
-
-# Script does not accept other arguments.
-if [ $# -gt 0 ]; then
-	output "Invalid argument." 1
-	script_exit 1
-fi
+proc_CL "$@"
 
 # Check bintray-debian-upload.conf
 if [ ! -f "$etclocation/bintray-debian-upload.conf" ]; then
